name: CI 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: ls
    - name: Run a multi-line script
      run: |
        echo "::set-env name=REPORT_PATH::test-sync/$GITHUB_SHA/$GITHUB_RUN_NUMBER/E2E/" 
        echo "::set-env name=TEST::hello" 
        echo "::set-env name=NODE_ENV::test" # https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        echo 'hi' 
        env
        echo $GITHUB_SHA
        echo $REPORT_PATH 
        echo $TEST
        echo $NODE_ENV
    - name: Run a line script
      run: |
        echo $GITHUB_SHA
        echo $REPORT_PATH 
        echo $TEST
        echo $NODE_ENV
